import { parseVoice, twoHands } from '../notation';
import type { Song } from '../types';

/** Exercícios técnicos usados nas lições iniciais. */
export const exercises: Song[] = [
  {
    id: 'ex-do-central',
    kind: 'exercise',
    title: 'Encontrando o Dó central',
    tempo: 70,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 1,
    instruments: ['piano', 'organ'],
    notes: parseVoice('C4/q:1 C4:1 C4:1 C4:1 | C4/h:1 C4/h:1', { hand: 'right' }),
  },
  {
    id: 'ex-do-re-mi',
    kind: 'exercise',
    title: 'Dó, Ré, Mi',
    tempo: 72,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 1,
    instruments: ['piano', 'organ'],
    notes: parseVoice('C4/q:1 D4:2 E4:3 D4:2 | C4/q:1 D4:2 E4/h:3 | E4/q:3 D4:2 C4/h:1', {
      hand: 'right',
    }),
  },
  {
    id: 'ex-cinco-dedos-md',
    kind: 'exercise',
    title: 'Cinco dedos — mão direita',
    tempo: 76,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 1,
    instruments: ['piano', 'organ'],
    notes: parseVoice('C4/q:1 D4:2 E4:3 F4:4 | G4/w:5 | G4/q:5 F4:4 E4:3 D4:2 | C4/w:1', {
      hand: 'right',
    }),
  },
  {
    id: 'ex-cinco-dedos-me',
    kind: 'exercise',
    title: 'Cinco dedos — mão esquerda',
    tempo: 76,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 1,
    instruments: ['piano', 'organ'],
    notes: parseVoice('C3/q:5 D3:4 E3:3 F3:2 | G3/w:1 | G3/q:1 F3:2 E3:3 D3:4 | C3/w:5', {
      hand: 'left',
    }),
  },
  {
    id: 'ex-maos-juntas',
    kind: 'exercise',
    title: 'Primeiras duas mãos',
    tempo: 70,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 2,
    instruments: ['piano', 'organ'],
    notes: twoHands(
      'C4/q:1 D4:2 E4:3 F4:4 | G4/h:5 E4/h:3 | F4/q:4 E4:3 D4:2 E4:3 | C4/w:1',
      'C3/w:5 | C3/w:5 | G2/w:5 | C3/w:5',
    ),
  },
  {
    id: 'ex-acordes-maiores',
    kind: 'exercise',
    title: 'Acordes de Dó, Fá e Sol',
    tempo: 66,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 2,
    instruments: ['piano', 'organ'],
    notes: parseVoice(
      '[C3 E3 G3]/w:5,3,1 | [C3 F3 A3]/w:5,2,1 | [B2 D3 G3]/w:5,3,1 | [C3 E3 G3]/w:5,3,1',
      { hand: 'left' },
    ),
  },
  {
    id: 'ex-escala-do',
    kind: 'exercise',
    title: 'Escala de Dó maior',
    tempo: 80,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 2,
    instruments: ['piano', 'organ'],
    notes: parseVoice(
      'C4/q:1 D4:2 E4:3 F4:1 | G4:2 A4:3 B4:4 C5:5 | C5:5 B4:4 A4:3 G4:2 | F4:1 E4:3 D4:2 C4:1',
      { hand: 'right' },
    ),
  },
  {
    id: 'ex-legato-orgao',
    kind: 'exercise',
    title: 'Legato no órgão',
    subtitle: 'Notas longas e ligadas, sem “buracos” entre elas',
    tempo: 60,
    timeSignature: [4, 4],
    keySignature: 0,
    difficulty: 1,
    instruments: ['organ'],
    notes: twoHands(
      'E4/h:3 F4/h:4 | G4/w:5 | F4/h:4 E4/h:3 | D4/w:2 | C4/w:1',
      'C3/w:5 | B2/w:5 | C3/w:5 | G2/w:5 | C3/w:5',
    ),
  },
];
